### ISSUE TITLE
Fails to compile api.c

### ISSUE THREAD

**Issue by dnojiri** [vpalatin/libsigrok#1]
src/hardware/ftdi-la/api.c: In function 'scan_device':
src/hardware/ftdi-la/api.c:123:4: warning: passing argument 2 of 'ftdi_usb_get_strings' from inc
ompatible pointer type [enabled by default]
    model, 32, serial_num, 32);
    ^
In file included from src/hardware/ftdi-la/api.c:21:0:
/usr/include/ftdi.h:376:9: note: expected 'struct usb_device *' but argument is of type 'struct
libusb_device *'
     int ftdi_usb_get_strings(struct ftdi_context *ftdi, struct usb_device *dev,
         ^
src/hardware/ftdi-la/api.c: In function 'scan_all':
src/hardware/ftdi-la/api.c:185:3: warning: passing argument 2 of 'scan_device' from incompatible
 pointer type [enabled by default]
   scan_device(ftdic, curdev->dev, &devices);                                                   
   ^                                                                                            
src/hardware/ftdi-la/api.c:85:13: note: expected 'struct libusb_device *' but argument is of typ
e 'struct usb_device *'                                                                         
 static void scan_device(struct ftdi_context *ftdic,

**Comment by vpalatin** [comment]
Please note that the pasted snippets only contains warnings (which are not failing the build), you should paste also the end of the log if the build actually fails.

by the way you don't really need libftdi or this driver, you can just pass '--without-libftdi' to configure

**Comment by dnojiri** [comment]
I ran:
$ make clean && ./autogen.sh && ./configure --prefix=/usr --without-libftdi && make

I got:
make  all-am                                                                                    
make[1]: Entering directory `/home/dnojiri/tmp/sigrok/libsigrok'               
make[1]: *** [bindings/python/timestamp] Error 1                                                
make[1]: Leaving directory `/home/dnojiri/tmp/sigrok/libsigrok'                
make: *** [all] Error 2

**Comment by vpalatin** [comment]
Either you have truncated the trace, or you did something like sudo make install and still have files.

Can you send a full build log ?

**Comment by dnojiri** [comment]
binding/python/setup was failing because pip and numpy were missing. I installed them and now 'sudo make install' succeeds. Thank you,
